config/routes.rb
PopUpStores::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:language)", locale: /en|es/ do 
    resources :markets, :only => [:index, :show] do
      collection do
        post :search, action: "search", as: 'search'
        get :search, action: "search"
        get :live_search, action: "live_search", path: "live_search"
      end
      post :publish
      post :publish_anyway
      post :unpublish
      post :archive
      get :make_pro_payment
      get :poster
      post :make_pro
      post :force_make_pro

      resource :statistic, controller: "statistic", :only => [] do
        get :market, :on => :member, :as => "show"
      end
    end

    get "/users/:id/dashboard", to: "users#user_dashboard", as: "user_dashboard"
    get "/users/admin", to: "users#admin", as: "admin"
    get "/users/:user_id/markets", to: "markets#list_user_markets", as: "user_markets"
    get "/published", to: "markets#list_published_markets", as: "published_markets"
    get "/list_recommend_markets", to: "markets#list_recommend_markets", as: "list_recommend_markets"

    get "/reindex", to: "markets#reindex", as: "market_reindex"
    get "/delete_index", to: "markets#delete_index", as: "market_delete_index"

    get "/users/gallery",  to: "users#gallery", as: "users_gallery"
    get "/users/like_market/:market_id",  to: "users#users_who_like_market", as: "users_who_like_market"
    get "/users/live_search", to: "users#live_search", path: "users_live_search"
    resources :users

    resources :slideshow_images, :except => [:show]
    resources :slideshow_texts, :except => [:show]

    resources :users do
      resources :markets, only: [:index, :new, :create, :edit, :update, :destroy]

      put :desactivate, :on => :member
      put :activate, :on => :member

      resource :role, controller: "role", :only => [:update] do
        get :change, :on => :member
      end

      resource :status, controller: "status", :only => [:update]

      resource :statistic, controller: "statistic", :only => [] do
        get :user, :on => :member, :as => "show"
      end

    end

    resources :subscriptions, :only => [:create] do

    end

    post "/unsubscribe", to: "subscriptions#unsubscribe", as: "unsubscribe"
    get "/users/:id/subscription", to: "users#subscription", as: "user_subscription"
    get "/users/:id/subscription_plan", to: "users#subscription_plan", as: "user_subscription_plan"

    resource :contact, controller: "contact", :only => [] do
      get :new, :on => :member
      post :create, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :market, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :admin, :on => :member, :as => "show"
    end

    get "coupons/buy_coupon_form/:id", to: "coupons#buy_coupon_form", as: "buy_coupon_form"
    get "/coupons/gallery", to: "coupons#gallery", as: "coupons_gallery"
    get "/coupons/localizador/:transaction_id", to: "coupons#localizador", as: "localizador"
    get "coupons/digest", to:"coupons#digest", as: "last_transactions"
    resources :coupons, :only => [:show, :index] do
      post :coupon_payment, :on => :member
    end

    post "/coupons/:id/buy", to: "coupons#buy", as: "buy_coupon"
    get "/coupons/:user_id/bought_coupons_by_user", to: "coupons#bought_coupons_by_user", as: "bought_coupons_by_user"
    get "/coupons/:market_id/sold_coupons_by_market", to: "coupons#sold_coupons_by_market", as: "sold_coupons_by_market"

    get "/wishes/gallery", as: "wishes_gallery"
    get "/users/:user_id/wishes", to: "wishes#list_user_wishes", as: "user_wishes"
    post "/wishes/:id/recommend/:market_id", to: "wishes#recommend", as: "recommend_market_to_wish"
    get "/users/:user_id/wishes_gallery", to: "wishes#gallery_user_wishes", as: "gallery_user_wishes"

    resources :wishes

    get "/bargains/gallery", as: "bargains_gallery"
    get "/users/:user_id/bargains", to: "bargains#list_user_bargains", as: "user_bargains"
    get "/users/:user_id/bargains_gallery", to: "bargains#gallery_user_bargains", as: "gallery_user_bargains"
    resources :bargains

    get "/likes/:user_id", to: "markets#list_liked_markets", as: "user_likes"
    get "/like/:market_id",  to: 'users#like', as: 'like'
    get "/unlike/:market_id",  to: 'users#unlike', as: 'unlike'

    get "/follow/:user_id",  to: 'users#follow', as: 'follow_user'
    get "/unfollow/:user_id",  to: 'users#unfollow', as: 'unfollow_user'

    get "/photos/:id/edit", to: "photos#edit", as: 'edit_photo'
    post "/photos/:id/crop", to: "photos#crop", as: 'crop_photo'
    get "/users/:user_id/photos", to: "photos#list_user_photos", as: "user_photos"
    resources :photos, only: [:show, :index, :destroy]
    resources :gallery, only: [:show]

    get "/last_markets", to: "markets#list_last_markets", as: "last_markets"
    get "/pro_markets", to: "markets#list_pro_markets", as: "pro_markets"
    get "/slideshow", to: "markets#slideshow", as: "slideshow"

    get "/special_locations/list", as: "special_locations_list"
    get "/special_locations/gallery", as: "special_locations_gallery"
    get "/special_locations/get_location", as: "get_location", path: "get_location"
    resources :special_locations

    get "/tags/list", as: "tags_list"
    get "/tags/suggested", as: "suggested_tags"
    get "/tags/gallery", as: "tags_gallery"
    get "/tags/:tag/markets", to: "markets#list_tag_markets", as: "tag_markets"
    resources :tags
   
    get "/categories/list", as: "categories_list"
    get "/categories/gallery", as: "category_gallery"
    get "/category/:category_id/markets", to: "markets#list_category_markets", as: "category_markets"
    resources :categories

    get "static_pages/map", path: "/map", as: 'map'
    get "static_pages/buy_coupon_terms", as: "buy_coupon_terms"
    get "static_pages/sell_coupon_terms", as: "sell_coupon_terms"
    get "static_pages/go_premium_terms", as: "go_premium_terms"
    get "static_pages/go_vim_terms", as: "go_vim_terms"
    get "static_pages/about", as: "about"
    get "static_pages/privacy", as: "privacy"
    get "static_pages/terms", as: "terms"
    get "static_pages/settings", path: "/settings", as: "settings"
    get "static_pages/beta", path: "/beta", as: "beta"
    get "static_pages/open_market_menu", path: "/open_market", as: "open_market"

    get "static_pages/home", path: "/", as: 'home'
    root "static_pages#home"

  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount Attachinary::Engine => "/attachinary"

end

app/models/bargain.rb
class Bargain
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :description, type: String
  field :price, type: String

  belongs_to :user, class_name: "User", inverse_of: :bargains

  has_one :photography, class_name: "Photo", as: :photographic, autobuild: true, dependent: :destroy
  accepts_nested_attributes_for :photography

  def self.icon
    "fa-bullhorn"
  end

  def aspect_ratio
    1
  end
end

app/controllers/bargains_controller.rb
class BargainsController < ApplicationController
  load_resource :only => [:show, :edit, :destroy, :update]
  authorize_resource :except => [:show, :list_user_bargains, :gallery_user_bargains, :gallery]

  def index
    @bargains = Bargain.all.desc(:created_at)
    respond_to do |format|
        format.html
        format.json {render json: @bargains}
    end
  end

  def gallery
    @bargains = Bargain.all.desc(:created_at).page(params[:page]).per(1)
    render :layout => !request.xhr?
  end

  def gallery_user_bargains
    @bargains = load_user.bargains.all.desc(:created_at).page(params[:page]).per(1)
    render "gallery"
  end

  def list_user_bargains
    @bargains = load_user.bargains.all.desc(:created_at)
    render "index"
  end

  def new
    if !current_user.too_many_bargains?
      @bargain = Bargain.new
    end
    render "form"
  end

  def show
  end

  def edit
    render "form"
  end

  def create
    @bargain = Bargain.new(bargain_params)
    @bargain.user = current_user
    respond_to do |format|
      if @bargain.save
        format.html { redirect_to user_bargains_path(current_user), notice: ControllerNotice.success('created', 'bargain')  }
      else
        format.html { redirect_to user_bargains_path(current_user), flash: { error:  ControllerNotice.fail('created', 'bargain') }}
      end
    end
  end

  def update
    respond_to do |format|
      if @bargain.update(bargain_params)
        format.html { redirect_to user_bargains_path(current_user), notice: ControllerNotice.success('updated', 'bargain')  }
      else
        format.html { redirect_to user_bargains_path(current_user), flash: { error:  ControllerNotice.fail('updated', 'bargain') }}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @bargain.destroy
        format.html { redirect_to user_bargains_path(current_user),
                      notice: ControllerNotice.success('deleted', 'bargain')  }
      else
        format.html { redirect_to user_bargains_path(current_user),
                      flash: { error:  ControllerNotice.fail('deleted', 'bargain')}}
      end
    end
  end

  private
    def bargain_params
      params.require(:bargain).permit(:description, :price, photography_attributes: [:photo])
    end

    def load_user
      User.find(params[:user_id])
    end

end

app/views/bargains/_form_fields.html.erb
<div class="form-group">
  <%= f.input :description, input_html: { placeholder: t(:description).capitalize }, required: true %>
</div>

<div class="form-group">
  <div class="input-group">
    <%= f.input_field :price, input_html: { placeholder: t(:price).capitalize }, required: true %>
    <span class="input-group-addon">€</span>
  </div>
</div>

<div class="form-group">
  <%= f.simple_fields_for :photography do |form_builder| %>
    <%= render 'photos/form', f: form_builder, required: true %>
  <% end %>
</div>

app/views/bargains/_show.html.erb
<%= stylesheet_link_tag 'bargains'%>

<div class="container main-container">
  <div class="container-inner row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default panel-table panel-table-last panel-bargain-show">
        <div class="panel-heading table-title center">
          <%= bargain.description %> <br>
          <h5>
            <%= t(:by) %>: <%= link_to bargain.user.name, bargain.user %>
          </h5>
        </div>
        <div class="bargain">
          <div class="bargain-photo-container">
            <%= photo(bargain.photography, 400) %> 
            <%= render "bargains/utils/price_badge", bargain: bargain %>
          </div>
          <div class="center">
            <%= render "bargains/utils/facebook", bargain: bargain %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bargains/_table_fields.html.erb
<div class="col-md-4"> 
  <div class="table-photo-container">
    <%= photo(entity.photography, 120) %>
    <%= render partial: 'photos/utils/actions', locals: { photo: entity.photography} %>
  </div>
</div>

<div class="col-md-2"> 
	<%= entity.description %> 
</div>

<div class="col-md-2"> 
	<%= entity.price %> € 
</div>

app/views/bargains/form.html.erb
<% if !current_user.too_many_bargains? %>
  <%= form(@bargain) %>
<% else %>
  <div class="creation-not-allowed">
    <%= too_many_bargains_message(current_user) %>
  </div>
  <div class="center">
    <%= back_link %>
  </div>
<% end %>

app/views/bargains/gallery.html.erb
<%= page_title(t(:bargains), Bargain.icon) %>

<% if current_user  %>
  <div class = "center">  
    <%= link_to new_bargain_path, class: "btn btn-default" do %>
      <i class="fa fa-plus"></i> <%= t :new_bargain %>
    <% end %>
  </div>
<% end %>

<div class="paginate">
  <%= paginate @bargains %>
</div>

<% if @bargains != [] %>
  <% @bargains.each do |bargain| %>
    <%= render "bargains/show", :bargain => bargain %>
  <% end %>
<% else %>
 <h1> <%= t(:no_bargains) %> :( </h1>
<% end %>

app/views/bargains/index.html.erb
<%= table(@bargains) %>

<div class = "center">
  <%= link_to bargains_gallery_path, class: "btn btn-default" do %>
    <%= t :all_bargains %>
  <% end %>
</div>

app/views/bargains/show.html.erb
<%= render "bargains/show", :bargain => @bargain %>