config/routes.rb
PopUpStores::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:language)", locale: /en|es/ do 
    resources :markets, :only => [:index, :show] do
      collection do
        post :search, action: "search", as: 'search'
        get :search, action: "search"
        get :live_search, action: "live_search", path: "live_search"
      end
      post :publish
      post :publish_anyway
      post :unpublish
      post :archive
      get :make_pro_payment
      get :poster
      post :make_pro
      post :force_make_pro

      resource :statistic, controller: "statistic", :only => [] do
        get :market, :on => :member, :as => "show"
      end
    end

    get "/users/:id/dashboard", to: "users#user_dashboard", as: "user_dashboard"
    get "/users/admin", to: "users#admin", as: "admin"
    get "/users/:user_id/markets", to: "markets#list_user_markets", as: "user_markets"
    get "/published", to: "markets#list_published_markets", as: "published_markets"
    get "/list_recommend_markets", to: "markets#list_recommend_markets", as: "list_recommend_markets"

    get "/reindex", to: "markets#reindex", as: "market_reindex"
    get "/delete_index", to: "markets#delete_index", as: "market_delete_index"

    get "/users/gallery",  to: "users#gallery", as: "users_gallery"
    get "/users/like_market/:market_id",  to: "users#users_who_like_market", as: "users_who_like_market"
    get "/users/live_search", to: "users#live_search", path: "users_live_search"
    resources :users

    resources :slideshow_images, :except => [:show]
    resources :slideshow_texts, :except => [:show]

    resources :users do
      resources :markets, only: [:index, :new, :create, :edit, :update, :destroy]

      put :desactivate, :on => :member
      put :activate, :on => :member

      resource :role, controller: "role", :only => [:update] do
        get :change, :on => :member
      end

      resource :status, controller: "status", :only => [:update]

      resource :statistic, controller: "statistic", :only => [] do
        get :user, :on => :member, :as => "show"
      end

    end

    resources :subscriptions, :only => [:create] do

    end

    post "/unsubscribe", to: "subscriptions#unsubscribe", as: "unsubscribe"
    get "/users/:id/subscription", to: "users#subscription", as: "user_subscription"
    get "/users/:id/subscription_plan", to: "users#subscription_plan", as: "user_subscription_plan"

    resource :contact, controller: "contact", :only => [] do
      get :new, :on => :member
      post :create, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :market, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :admin, :on => :member, :as => "show"
    end

    get "coupons/buy_coupon_form/:id", to: "coupons#buy_coupon_form", as: "buy_coupon_form"
    get "/coupons/gallery", to: "coupons#gallery", as: "coupons_gallery"
    get "/coupons/localizador/:transaction_id", to: "coupons#localizador", as: "localizador"
    get "coupons/digest", to:"coupons#digest", as: "last_transactions"
    resources :coupons, :only => [:show, :index] do
      post :coupon_payment, :on => :member
    end

    post "/coupons/:id/buy", to: "coupons#buy", as: "buy_coupon"
    get "/coupons/:user_id/bought_coupons_by_user", to: "coupons#bought_coupons_by_user", as: "bought_coupons_by_user"
    get "/coupons/:market_id/sold_coupons_by_market", to: "coupons#sold_coupons_by_market", as: "sold_coupons_by_market"

    get "/wishes/gallery", as: "wishes_gallery"
    get "/users/:user_id/wishes", to: "wishes#list_user_wishes", as: "user_wishes"
    post "/wishes/:id/recommend/:market_id", to: "wishes#recommend", as: "recommend_market_to_wish"
    get "/users/:user_id/wishes_gallery", to: "wishes#gallery_user_wishes", as: "gallery_user_wishes"

    resources :wishes

    get "/bargains/gallery", as: "bargains_gallery"
    get "/users/:user_id/bargains", to: "bargains#list_user_bargains", as: "user_bargains"
    get "/users/:user_id/bargains_gallery", to: "bargains#gallery_user_bargains", as: "gallery_user_bargains"
    resources :bargains

    get "/likes/:user_id", to: "markets#list_liked_markets", as: "user_likes"
    get "/like/:market_id",  to: 'users#like', as: 'like'
    get "/unlike/:market_id",  to: 'users#unlike', as: 'unlike'

    get "/follow/:user_id",  to: 'users#follow', as: 'follow_user'
    get "/unfollow/:user_id",  to: 'users#unfollow', as: 'unfollow_user'

    get "/photos/:id/edit", to: "photos#edit", as: 'edit_photo'
    post "/photos/:id/crop", to: "photos#crop", as: 'crop_photo'
    get "/users/:user_id/photos", to: "photos#list_user_photos", as: "user_photos"
    resources :photos, only: [:show, :index, :destroy]
    resources :gallery, only: [:show]

    get "/last_markets", to: "markets#list_last_markets", as: "last_markets"
    get "/pro_markets", to: "markets#list_pro_markets", as: "pro_markets"
    get "/slideshow", to: "markets#slideshow", as: "slideshow"

    get "/special_locations/list", as: "special_locations_list"
    get "/special_locations/gallery", as: "special_locations_gallery"
    get "/special_locations/get_location", as: "get_location", path: "get_location"
    resources :special_locations

    get "/tags/list", as: "tags_list"
    get "/tags/suggested", as: "suggested_tags"
    get "/tags/gallery", as: "tags_gallery"
    get "/tags/:tag/markets", to: "markets#list_tag_markets", as: "tag_markets"
    resources :tags
   
    get "/categories/list", as: "categories_list"
    get "/categories/gallery", as: "category_gallery"
    get "/category/:category_id/markets", to: "markets#list_category_markets", as: "category_markets"
    resources :categories

    get "static_pages/map", path: "/map", as: 'map'
    get "static_pages/buy_coupon_terms", as: "buy_coupon_terms"
    get "static_pages/sell_coupon_terms", as: "sell_coupon_terms"
    get "static_pages/go_premium_terms", as: "go_premium_terms"
    get "static_pages/go_vim_terms", as: "go_vim_terms"
    get "static_pages/about", as: "about"
    get "static_pages/privacy", as: "privacy"
    get "static_pages/terms", as: "terms"
    get "static_pages/settings", path: "/settings", as: "settings"
    get "static_pages/beta", path: "/beta", as: "beta"
    get "static_pages/open_market_menu", path: "/open_market", as: "open_market"

    get "static_pages/home", path: "/", as: 'home'
    root "static_pages#home"

  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount Attachinary::Engine => "/attachinary"

end

app/views/layouts/shared/_add_market.html.erb
<li class="registered-user-action ">
  <%= button_to "✚", open_market_path , class:"add_market_button btn btn-default", :method => :get %>
</li>

<script>
  $(document).ready(function(){
    checkIfMobileButton();
    $(window).bind('resize', checkIfMobileButton);
  });

  function checkIfMobileButton(){
    if (window.innerWidth >= 992){
      $(".add_market_button").val("<%= t(:new_market) %>");
    }
    else if (window.innerWidth >= 768){
      $(".add_market_button").val("✚ <%= t(:market).capitalize %>");
    }
    else{
      $(".add_market_button").val("✚");
    }
  }
</script>

app/views/layouts/shared/_admin_menu.html.erb
<li>
  <%= link_to admin_path, class:"btn btn-xs btn-primary btn-lg btn-100" do %>
      <i class="fa fa-cog"></i> <%= t(:admin_panel) %>
  <% end %>
  <%= link_to user_dashboard_path(current_user), class:"btn btn-xs btn-info btn-lg btn-100" do %>
      <i class="fa fa-dashboard"></i> <%= t(:dashboard).capitalize %>
  <% end %>
</li>

app/views/layouts/shared/_cookies_policy.html.erb
<!-- Copyright (c) OpenGlobal. GNU/GPL V3 licence. You may copy and modify this, providing the link to http://www.openglobal.co.uk remains intact. -->

<div id="openglobal_privacy_widget">
  <%= t(:accept).capitalize %> <%= link_to "cookies", privacy_path %>?
  <button id="openglobal_privacy_accept" style="vertical-align: middle;" onclick="openglobal_privacy_accept();return false;"><%= t(:proceed) %></button>
</div>

<script type="text/javascript">
//<![CDATA[
var openglobal_privacy_timeout = 0;
var openglobal_privacy_functions = [];

var openglobal_privacy_widget = document.getElementById('openglobal_privacy_widget');
var results = document.cookie.match ( '(^|;) ?openglobal_privacy_widget=([^;]*)(;|$)' );
if (results) {
  if (1 == unescape(results[2])) {
    openglobal_privacy_accept();
  }
} else {
  window.onload = function() {
    for (var i = 0; i < document.links.length; i++) {
      var link_href = document.links[i].getAttribute('href');
      if ('privacy' != document.links[i].getAttribute('rel') && (!/^[\w]+:/.test(link_href) || (new RegExp('^[\\w]+://[\\w\\d\\-\\.]*' + window.location.host)).test(link_href))) {
        var current_onclick = document.links[i].onclick;
document.links[i].onclick = function() {openglobal_privacy_accept();if (Object.prototype.toString.call(current_onclick) == '[object Function]') {current_onclick();}};
      }
    }
  };
}

var openglobal_privacy_timer;
if (openglobal_privacy_timeout > 0) {
   openglobal_privacy_timer = setTimeout('openglobal_privacy_tick()', 1000);
} else {
  var openglobal_privacy_wait = document.getElementById('openglobal_privacy_wait');
  if (null != openglobal_privacy_wait) {
    openglobal_privacy_wait.parentNode.removeChild(openglobal_privacy_wait);
  }
}
function openglobal_privacy_tick() {
  if (0 >= --openglobal_privacy_timeout) {
    openglobal_privacy_accept();
    return;
  }
  var openglobal_privacy_accept_button = document.getElementById('openglobal_privacy_accept');
  if (null != openglobal_privacy_accept_button) {
    openglobal_privacy_accept_button.innerHTML = 'Yes (' + openglobal_privacy_timeout + ')';
    openglobal_privacy_timer = setTimeout('openglobal_privacy_tick()', 1000);
  }
}

function openglobal_privacy_accept() {
  clearTimeout(openglobal_privacy_timer);
  document.cookie = 'openglobal_privacy_widget=1; path=/; expires=Mon, 18 Jan 2038 03:14:00 GMT';
  openglobal_privacy_widget.parentNode.removeChild(openglobal_privacy_widget);
  for (var i = 0; i < openglobal_privacy_functions.length; i++) {
    openglobal_privacy_functions[i]();
  }
}
//]]>
</script>

app/views/layouts/shared/_flash.html.erb
<section id="messages">
  <% if flash[:notice] %>
    <div id="notice" class="alert alert-success flash"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:warning] %>
    <div id="warning" class="alert alert-warning flash"><%= flash[:warning] %></div>
  <% end %>

  <% if flash[:error] %>
    <div id="error" class="alert alert-danger flash"><%= flash[:error] %></div>
  <% end %>
</section>

<script>
	setTimeout(function(){
	 $("#notice").slideUp(800);
	     }, 1200);
  setTimeout(function(){
   $("#warning").slideUp(800);
       }, 1200);
  setTimeout(function(){
   $("#error").slideUp(800);
       }, 1200);
</script>

<style>
	.alert{
		margin-bottom:0px;
	}
</style>

app/views/layouts/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom hidden-xs" role="navigation">
  <div class="container">
    <p class="navbar-text"> 
      <span class="hidden-md hidden-sm"> Copyright &copy; DOWEMARKET 2014</span>
      <span class="footer-link"><%= link_to t(:privacy).capitalize, privacy_path %></span>
      <span class="footer-link"><%= link_to t(:terms_of_use).capitalize, terms_path %></span>
      <span class="footer-link"><%= link_to t(:about), about_path %></span>
    </p>
    <ul class="nav navbar-nav navbar-right footer-right">
      <%= render "layouts/shared/user_city" %>
      <%= render "layouts/shared/footer_menu" %>
    </ul>
  </div>
</nav>

<style>
	.popover{
		width:300px;
	}
	.input-group{
		width:100%;
	}
	.input-content{
    text-align: left;
	}

  .fa-exclamation-triangle{
    color: #FFB834;
  }

  #user-city-text > .fa-crosshairs{
    color: #1981CF;
  }

  #user-city-text{
    text-overflow: ellipsis;
    width: 200px;
    white-space: nowrap;
    overflow: hidden;
  }

  .user_city{
    padding-left:15px;
  }

  @media (min-width: 767px){
    .language-toggle{
      font-weight: normal !important;
      width:70px !important;
    }
  
    .contact-button{
      font-weight: normal !important;
    }
  }

</style>

app/views/layouts/shared/_footer_menu.html.erb
<li class="languages footer-collapse">
  <a href="#" class="dropdown-toggle language-toggle" data-toggle="dropdown">
    <span class="current-language"><%= I18n.locale.to_s.upcase %></span>
    <b class="caret"></b>
  </a>

  <ul class="dropdown-menu language-select">
    <li><%= link_to "English (EN)", :language => :en %></li>
    <li><%= link_to "Español (ES)", :language => :es %></li>
  </ul>
</li>

<script>
$(".language-select li a").click(function(){
  var languageSelected = $(this).attr("name");
  $('.current-language').html(languageSelected);
});
</script>
        
<li class="contact-us footer-collapse">
  <a href="/contact" class="contact-button">
  	<i class="fa fa-envelope"></i>&nbsp;
  	<span class="hidden-sm hidden-md"><%= t(:contact_us) %></span>
  </a>
</li>

app/views/layouts/shared/_guest_menu.html.erb
<li class="dropdown mega-dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-list-ul"></i>
    <span id="explore-link-text" class="hidden-sm hidden-md">&nbsp;<%= t(:explore).capitalize %></span>
    <b class="caret"></b>
  </a>
  
  <ul class="dropdown-menu mega-dropdown-menu row">
    <li class="col-sm-3">
      <ul class="explore_section">
        <li class="item-title"><%= t :whats_new %></li>
        <li class="divider"></li>
        <li class="registered-user-action">
          <%= link_to published_markets_path do %>
            <%= t :all_markets %><i class="fa fa-angle-right explore-arrow"></i>
          <% end %>
        </li>
        <li class="divider"></li>                           
          <div id="myCarousel" class="hidden-xs carousel slide" data-ride="carousel">
            <div class="carousel-inner" id="carousel-latest-markets"></div>
          </div>
      </ul>
    </li>

    <li class="col-sm-3">
      <ul id="explore_categories" class="explore_section">
        <li class="item-title"><%= t(:categories).capitalize %></li>
        <li class="divider"></li>
      </ul>
    </li>

    <li class="col-sm-2">
      <ul id="explore_tags" class="explore_section">
        <li class="item-title"><%= t(:tags).capitalize %></li>  
        <li class="divider"></li>
      </ul>
    </li>

    <li class="col-sm-2">
      <ul id="explore_hotspots" class="explore_section">
        <li class="item-title"><%= t(:hot_spots).capitalize %></li>
        <li class="divider"></li>  
      </ul>
    </li>

    <li class="col-sm-2">
      <ul class="explore_section">
        <li class="item-title"><%= t(:more) %></li>
        <li class="divider"></li>
        <li class="registered-user-action">
          <%= link_to wishes_gallery_path do %>
            <%= t(:all_wishes).capitalize %><i class="fa fa-angle-right explore-arrow"></i>
          <% end %>
        </li>
        <li class="registered-user-action">
          <%= link_to bargains_gallery_path do %>
            <%= t(:all_bargains).capitalize %><i class="fa fa-angle-right explore-arrow"></i>
          <% end %>
        </li>
        <li class="registered-user-action">
          <%= link_to coupons_gallery_path do %>
            <%= t(:all_coupons).capitalize %><i class="fa fa-angle-right explore-arrow"></i>
          <% end %>
        </li>
        <li class="registered-user-action">
          <%= link_to users_live_search_path do %>
            <%= t(:all_users).capitalize %><i class="fa fa-angle-right explore-arrow"></i>
          <% end %>
        </li>
      </ul>
    </li>
  </ul> 
</li>

<script>
  $.get( "/slideshow", function( data ) {
      $( "#carousel-latest-markets" ).html( data );
    });

    $.ajax({url: "/categories/list", 
       data: { language: "<%= params['language'] %>"}
    }).done(function( data ) {
      $( "#explore_categories" ).append( data );
    });

    $.ajax({url: "/special_locations/list", 
       data: { language: "<%= params['language'] %>"}
    }).done(function( data ) {
      $( "#explore_hotspots" ).append( data );
    });


    $.ajax({url: "/tags/list", 
       data: { language: "<%= params['language'] %>"}
    }).done(function( data ) {
      $( "#explore_tags" ).append( data );
    });
</script>

<style>
  @media (min-width:768px){
    .mega-dropdown-menu > li > ul > li > a {
      overflow:hidden;
      float:inherit;
      white-space:nowrap;
      text-overflow: ellipsis;
    }
  }
</style>

app/views/layouts/shared/_header.html.erb
<head>
  <title>dowemarket</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= favicon_link_tag '/images/favicon.png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  
  <%= cloudinary_js_config %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>

  <!-- for Google -->
  <meta name="description" content="<%= t(:header_content) %>" />
  <meta name="keywords" content="<%= t(:header_keywords) %>" />
  <meta name="author" content="dowemarket" />
  <meta name="copyright" content="dowemarket" />
  <meta name="application-name" content="dowemarket" />
  
  <!-- for Facebook -->          
  <meta property="og:title" content="dowemarket" />
  <meta property="og:type" content="<%= t(:header_type) %>" />
  <meta property="og:image" content="/images/logo.jpg" />
  <meta property="og:url" content="http://dowemarket.com" />
  <meta property="og:description" content="<%= t(:header_content) %>" />
  
  <!-- for Twitter -->          
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="dowemarket" />
  <meta name="twitter:description" content="<%= t(:header_content) %>" />
  <meta name="twitter:image" content="/images/logo.jpg" />

  <!-- for iOS -->
  <link href="/images/apple-touch-icon.png" rel="apple-touch-icon" />
  <link href="/images/apple-touch-icon-precomposed.png" rel="apple-touch-icon-precomposed" />

</head>

app/views/layouts/shared/_navbarhorizontal.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <%= link_to beta_path do %>
      <div id="beta-badge-container">
        <div class="beta-badge">
          <span class="badge-text"></span>
        </div>
      </div>
    <% end %>

    <div class="navbar-header pull-left">
      <button type="button" class="navbar-toggle pull-left navbar-collapse-button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "dowemarket", home_path, :class => "navbar-brand" %>
    </div>

    <div class="navbar-header pull-right add-market-button-container">
      <ul class="nav pull-right">
        <%= render "layouts/shared/add_market" %>
      </ul>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render "layouts/shared/search_bar" %>
      </ul>
       
      <ul class="nav navbar-nav navbar-right topbar-right">
        <li class="map-link">
          <% if search_on_map? %> 
            <%= link_to search_markets_path do %>
              <i class="fa fa-search">
              </i><span id="search-link-text" class="hidden-sm hidden-md">
              &nbsp;<%= t(:search).capitalize %>...</span>
            <% end %>
          <% else %>
            <%= link_to map_path do %>
              <i class="fa fa-globe"></i>
              <span id="map-link-text" class="hidden-sm hidden-md">
                &nbsp;<%= t(:map).capitalize %> 
              </span>
            <% end %>
          <% end %>
        </li>
         
        <%= render "layouts/shared/guest_menu" %>
        <% if user_signed_in? %>
          <%= render "layouts/shared/signout" %>
        <% else %>
          <%= render "layouts/shared/signin" %>
        <% end %>
        <%= render "layouts/shared/footer_menu" %>
      </ul>

    </div>
  </div>
</nav>

<style>
  @media (min-width: 768px){
    .topbar-right > .footer-collapse{
      display:none;
    }
  }
</style>

<script>
  $(document).ready(function(){
    footerCollapse();
    window.onresize = footerCollapse();
  });
  
  var toggleDropup = function(widthBoolean){
    $(".languages").toggleClass("dropup", widthBoolean);
    $(".languages").toggleClass("dropdown", !widthBoolean);
  }
  
  var footerCollapse = function(){
    if (window.innerwidth > 768)
      toggleDropup(true);
    else
      toggleDropup(false);
  }
</script>

app/views/layouts/shared/_search_bar.html.erb
<li id="search_bar">
  <div class="input-group input-group">
    <%= text_field_tag :query, 
    session[:query], 
    placeholder: t(:search_markets), 
    class: "query form-control", 
    id: "search_bar_query" %>
    
    <span class="input-group-btn">

      <button class="btn btn-default" id="search_button" type="button">
         <% if search_on_map? %> 
            <i class="fa fa-globe"></i>
         <% else %>
            <i class="fa fa-search"></i>
        <% end %>
      </button>
    </span> 
  </div>
</li>

<script>
  var largeSearchBar = false;
  
  $( document ).ready(function() {
    
    $( "#search_bar_query").keypress(function(e) {
      if(e.keyCode == 13 ) {
        e.preventDefault();
        $("#search_button").click();
      }
    });
  
    $( "#search_bar_query" ).keyup(function() {
      $("#query").val($( "#search_bar_query" ).val());
    });
  
    $("#search_bar_query").focus(function(){
      if (window.innerWidth >= 768 && window.innerWidth < 1024)
        changeSearchBarSize(240, false);
      else if (window.innerWidth >= 1024)
        changeSearchBarSize(300, false);
    });
  
    $("#search_bar_query").focusout(function(){
      if (window.innerWidth >= 768 && window.innerWidth < 1024)
        changeSearchBarSize(200, true);
      else if (window.innerWidth >= 1024)
        changeSearchBarSize(240, true);
    });
  
    $("#search_button").click(function(){
      <% if search_page? %>
        $("#search_market").change();
      <% else %>
        $("#search_market").submit();
      <% end %>
    });
  });
  
  var changeSearchBarSize = function(newsize, flag){
    if (largeSearchBar == flag){
      $("#search_bar").animate({
        width: newsize
      }, 400, function(){
        largeSearchBar = !flag;
      });
    }
  };
</script>

<style>
  @media (min-width:768px) {
    #search_bar{
      margin-top: 8px;
      width: 200px;
    }
  }

  @media (min-width:1024px) {
    #search_bar{
      margin-top: 8px;
      width: 240px;
    }
  }
</style>

app/views/layouts/shared/_signin.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle sign-in-link" data-toggle="dropdown">
    <i class="fa fa-user"></i>&nbsp;<%= t(:sign_in).capitalize %><b class="caret"></b>
  </a>

  <ul class="dropdown-menu" style="padding: 15px;min-width: 250px;">
    <li>
      <div class="row">
        <div class="col-md-12 user-session-menu">
          <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
            <div class="form-group">
              <%= f.input :email, :required => true, :autofocus => true %>
            </div>

            <div class="form-group">
              <%= f.input :password, :required => true %>
            </div>

            <div class="form-group">
              <%= f.check_box :remember_me, as: :boolean, inline_label: t(:remember_me), label: false if devise_mapping.rememberable? %> <%= t(:remember_me) %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, t(:sign_in).capitalize , :class=>  "btn btn-info btn-block sign-in-button " %>
            </div>

            <div class="divider"></div>
          <% end %>
          <%= render "devise/shared/links" %>
        </div>
      </div>
    </li>
    <li class="divider"></li>
    <li class="omniauth-sign-up">
      <li> <%= button_to t(:sign_in_with_google), user_omniauth_authorize_path(:google_oauth2), :class=>  "btn btn-primary btn-block"  %> </li>
      <li> <%= button_to t(:sign_in_with_facebook), user_omniauth_authorize_path(:facebook), :class=>  "btn btn-primary btn-block" %></li>
    </li>
  </ul>
</li>

<style>
  .center{
    text-align: center;
  }
</style>

app/views/layouts/shared/_signout.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <% if current_user.has_role? "premium" %>
      <i class="fa fa-star premium-star"></i>
    <% end %>

    <% if current_user.image? %>
      <img src="<%= current_user.image %>" class="img img-circle" style="width: 20px; height: 20px;">
    <% else %>
      <i class="fa fa-user"></i>
    <% end %>

    <span id="nav_user_container"><span id="nav_user_name"><%=current_user.email%></span><b class="caret"></b></span>
  </a>

  <ul class="dropdown-menu" style="padding: 15px;min-width: 250px;">
    <div class="well well-sm">
      <div class="media">
        <a class="thumbnail pull-left" href="#">
          <img class="media-object" src="<%= current_user.image? ? current_user.image : 'http://critterapp.pagodabox.com/img/user.jpg' %>">
        </a>

        <div class="media-body">
          <% if current_user.has_role? "admin" %>
            <%= render "layouts/shared/admin_menu" %>
          <% else %>
            <%= render "layouts/shared/user_menu"  %>
          <% end %>
        </div>

      </div>

      <div class="form-actions center">
        <%= t(:you_are_signed_in_as) %> 
        <span style="color: #5bc0de;"><%=current_user.email%></span>
      </div>
    </div>

    <div class="form-actions">
      <%= link_to t(:sign_out), destroy_user_session_path, :class=>  "btn btn-info btn-block"  %>
    </div>
  </ul>
</li>

<style>
  #nav_user_container{
    display:inline-block;
  }

  @media (min-width:768px) {
    #nav_user_name{
      max-width:75px;
      float:left;
      overflow:hidden;
      white-space:nowrap;
      text-overflow: ellipsis;
    }
  }
  
  .center{
    text-align: center;
  }
  .btn-100{
    width: 100%;
  }
</style>

app/views/layouts/shared/_user_city.html.erb
<li class="user_city footer-collapse">
  <span class="navbar-text" id="user-city-text"></span>
</li>

app/views/layouts/shared/_user_menu.html.erb
<li>
  <%= link_to user_dashboard_path(current_user), class:"btn btn-xs btn-info btn-lg btn-100" do %>
    <i class="fa fa-dashboard"></i> <%= t(:dashboard).capitalize %>
  <% end %>

  <%= link_to user_markets_path(current_user), class:"btn btn-xs btn-danger btn-lg btn-100" do %>
    <i class="fa fa-shopping-cart"></i> <%= t(:markets).capitalize %>
  <% end %>

  <%= link_to user_likes_path(current_user), class:"btn btn-xs btn-warning btn-lg btn-100" do %>
    <i class="fa fa-heart-o"></i> <%= t(:likes).capitalize %>
  <% end %>
</li>