config/routes.rb
PopUpStores::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:language)", locale: /en|es/ do 
    resources :markets, :only => [:index, :show] do
      collection do
        post :search, action: "search", as: 'search'
        get :search, action: "search"
        get :live_search, action: "live_search", path: "live_search"
      end
      post :publish
      post :publish_anyway
      post :unpublish
      post :archive
      get :make_pro_payment
      get :poster
      post :make_pro
      post :force_make_pro

      resource :statistic, controller: "statistic", :only => [] do
        get :market, :on => :member, :as => "show"
      end
    end

    get "/users/:id/dashboard", to: "users#user_dashboard", as: "user_dashboard"
    get "/users/admin", to: "users#admin", as: "admin"
    get "/users/:user_id/markets", to: "markets#list_user_markets", as: "user_markets"
    get "/published", to: "markets#list_published_markets", as: "published_markets"
    get "/list_recommend_markets", to: "markets#list_recommend_markets", as: "list_recommend_markets"

    get "/reindex", to: "markets#reindex", as: "market_reindex"
    get "/delete_index", to: "markets#delete_index", as: "market_delete_index"

    get "/users/gallery",  to: "users#gallery", as: "users_gallery"
    get "/users/like_market/:market_id",  to: "users#users_who_like_market", as: "users_who_like_market"
    get "/users/live_search", to: "users#live_search", path: "users_live_search"
    resources :users

    resources :slideshow_images, :except => [:show]
    resources :slideshow_texts, :except => [:show]

    resources :users do
      resources :markets, only: [:index, :new, :create, :edit, :update, :destroy]

      put :desactivate, :on => :member
      put :activate, :on => :member

      resource :role, controller: "role", :only => [:update] do
        get :change, :on => :member
      end

      resource :status, controller: "status", :only => [:update]

      resource :statistic, controller: "statistic", :only => [] do
        get :user, :on => :member, :as => "show"
      end

    end

    resources :subscriptions, :only => [:create] do

    end

    post "/unsubscribe", to: "subscriptions#unsubscribe", as: "unsubscribe"
    get "/users/:id/subscription", to: "users#subscription", as: "user_subscription"
    get "/users/:id/subscription_plan", to: "users#subscription_plan", as: "user_subscription_plan"

    resource :contact, controller: "contact", :only => [] do
      get :new, :on => :member
      post :create, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :market, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :admin, :on => :member, :as => "show"
    end

    get "coupons/buy_coupon_form/:id", to: "coupons#buy_coupon_form", as: "buy_coupon_form"
    get "/coupons/gallery", to: "coupons#gallery", as: "coupons_gallery"
    get "/coupons/localizador/:transaction_id", to: "coupons#localizador", as: "localizador"
    get "coupons/digest", to:"coupons#digest", as: "last_transactions"
    resources :coupons, :only => [:show, :index] do
      post :coupon_payment, :on => :member
    end

    post "/coupons/:id/buy", to: "coupons#buy", as: "buy_coupon"
    get "/coupons/:user_id/bought_coupons_by_user", to: "coupons#bought_coupons_by_user", as: "bought_coupons_by_user"
    get "/coupons/:market_id/sold_coupons_by_market", to: "coupons#sold_coupons_by_market", as: "sold_coupons_by_market"

    get "/wishes/gallery", as: "wishes_gallery"
    get "/users/:user_id/wishes", to: "wishes#list_user_wishes", as: "user_wishes"
    post "/wishes/:id/recommend/:market_id", to: "wishes#recommend", as: "recommend_market_to_wish"
    get "/users/:user_id/wishes_gallery", to: "wishes#gallery_user_wishes", as: "gallery_user_wishes"

    resources :wishes

    get "/bargains/gallery", as: "bargains_gallery"
    get "/users/:user_id/bargains", to: "bargains#list_user_bargains", as: "user_bargains"
    get "/users/:user_id/bargains_gallery", to: "bargains#gallery_user_bargains", as: "gallery_user_bargains"
    resources :bargains

    get "/likes/:user_id", to: "markets#list_liked_markets", as: "user_likes"
    get "/like/:market_id",  to: 'users#like', as: 'like'
    get "/unlike/:market_id",  to: 'users#unlike', as: 'unlike'

    get "/follow/:user_id",  to: 'users#follow', as: 'follow_user'
    get "/unfollow/:user_id",  to: 'users#unfollow', as: 'unfollow_user'

    get "/photos/:id/edit", to: "photos#edit", as: 'edit_photo'
    post "/photos/:id/crop", to: "photos#crop", as: 'crop_photo'
    get "/users/:user_id/photos", to: "photos#list_user_photos", as: "user_photos"
    resources :photos, only: [:show, :index, :destroy]
    resources :gallery, only: [:show]

    get "/last_markets", to: "markets#list_last_markets", as: "last_markets"
    get "/pro_markets", to: "markets#list_pro_markets", as: "pro_markets"
    get "/slideshow", to: "markets#slideshow", as: "slideshow"

    get "/special_locations/list", as: "special_locations_list"
    get "/special_locations/gallery", as: "special_locations_gallery"
    get "/special_locations/get_location", as: "get_location", path: "get_location"
    resources :special_locations

    get "/tags/list", as: "tags_list"
    get "/tags/suggested", as: "suggested_tags"
    get "/tags/gallery", as: "tags_gallery"
    get "/tags/:tag/markets", to: "markets#list_tag_markets", as: "tag_markets"
    resources :tags
   
    get "/categories/list", as: "categories_list"
    get "/categories/gallery", as: "category_gallery"
    get "/category/:category_id/markets", to: "markets#list_category_markets", as: "category_markets"
    resources :categories

    get "static_pages/map", path: "/map", as: 'map'
    get "static_pages/buy_coupon_terms", as: "buy_coupon_terms"
    get "static_pages/sell_coupon_terms", as: "sell_coupon_terms"
    get "static_pages/go_premium_terms", as: "go_premium_terms"
    get "static_pages/go_vim_terms", as: "go_vim_terms"
    get "static_pages/about", as: "about"
    get "static_pages/privacy", as: "privacy"
    get "static_pages/terms", as: "terms"
    get "static_pages/settings", path: "/settings", as: "settings"
    get "static_pages/beta", path: "/beta", as: "beta"
    get "static_pages/open_market_menu", path: "/open_market", as: "open_market"

    get "static_pages/home", path: "/", as: 'home'
    root "static_pages#home"

  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount Attachinary::Engine => "/attachinary"

end

app/views/markets/shared/views/_full_view.html.erb
<div class="container main-container">
  <%= stylesheet_link_tag "markets/full-description" %>

  <div class="panel panel-default panel-table panel-table-last row market-full-description-panel">
    <%= render partial: 'markets/shared/utils/status', locals: { market: market } %>
    
    <%= render partial: 'markets/shared/utils/title_and_actions_bar', locals: { market: market } %>

    <div class="market-full-description-container">

      <div class="market-badge">
        <div class="ribbon-badge <%= market.badges %>">
          <span class="badge-text"></span>
        </div>
      </div>

      <div class="market-section-title row"><%= t(:general_information).capitalize %> 
        <%= market.direct_edit_link("form-market-description") %>
      </div>
      
      <div class="market-section-container row">
        <div class="col-md-6 market-photo">
          <%= market.market_featured_photo_filtered(400) %>
          <%= render partial: 'photos/utils/actions', locals: { photo: market.featured  } %>
        </div>
      
          
        <%= render partial: 'markets/shared/utils/description', locals: { market: market } %>
      </div>

      <div class="market-section-title row"><%= t(:schedule).capitalize %> 
        <%= market.direct_edit_link("form-market-date") %>
      </div>
      
      <div class="market-section-container row">
        <%= render partial: 'markets/shared/utils/calendar', locals: { market: market } %>
        <%= render partial: 'markets/shared/utils/schedule', locals: { market: market } %>
      </div>
    
       
      <% if !market.pro? && false%>
        <div class="adsense-banner">ADVERTISEMENT <span>POWERED BY ADSENSE</span>
        </div>
      <% end %>

      <%= market.photo_slideshow_section %>

      <%= market.photo_gallery_section if market.pro? %>
    
      <%= market.coupon_section if market.pro?  %>
      
      <div class="market-section-title row">
        <%= t(:location).capitalize %>
        <%= market.direct_edit_link("form-market-location") %>
      </div>
      
      <div class="market-section-container row"> 
        <div class="market-address-detail ">
          <%= market.address_and_city %>
        </div>
        <%= market.location %>
      </div>

      <div class="market-section-title row facebook-section">
        <%= t(:comments_and_share).capitalize %>
      </div>
      
      <div class="market-section-container row social-container facebook-section">
        <%= render partial: 'markets/shared/utils/facebook_comments', locals: { market: market } %>
      </div>
      
      <%= market.market_quality_section %>

  </div>
</div>


<style>
@media(max-width: 650px){
  .facebook-section{
    display:none;
  }
}
</style>

app/views/markets/shared/views/_gallery.html.erb
<div class = "market_gallery row ">

  <% markets.each do |market| %>
    <% market = market.decorate %>
    <%= content_tag_for(:tr, market) do %>
      <div class = "market_item col-md-4">
      
        <div class = "show gallery_market_featured_photo">

          <div class="market-badge">
            <div class="ribbon-badge <%= market.badges %>">
              <span class="badge-text"></span>
            </div>
          </div>
          
          <%= link_to market do %>
          <%= market.market_featured_photo_filtered(300) %>

          <div class = "market_name_label">
            <span><%= market.formatted_market_name %></span>
          </div>

          <div class = "market_description_label">
            <span><%= market.description %></span>
          </div>
          <% end %>
          <span class="like-badge <%= market.like_class %>"><%= market.like_badge_link %></span>
        </div> 

        <div class="market-gallery-extra">
          <%= market.market_like_count %><br>
          <% if !market.address.nil? %>
            <%= market.address.capitalize %>, <%= market.city %><br>
          <% end %>
          <%= market.market_date_highlight %>
        </div>
      </div>
    <% end %>
  <% end %>
  
</div>



<script>
$(document).ready(function(){
  if(<%= !user_signed_in? %>)
    $(".like-badge").hide();
  $(".like-badge").hover(function(){
    $(this).width(60);
    $(this).find('.like-icon').html("<i class='fa fa-heart'></i>&nbsp;&nbsp;Like");
    $(this).find('.unlike-icon').html("<i class='fa fa-times'></i>&nbsp;&nbsp;Unlike");
  }, function(){
    $(this).width(30);
    $(this).find('.like-icon').html("<i class='fa fa-heart-o'></i>");
    $(this).find('.unlike-icon').html("<i class='fa fa-heart'></i>");
  });
});
</script>

app/views/markets/shared/views/_recommend.html.erb
<% markets.each do |market| %>
  <div class="wish-recommended-item col-md-6 col-md-offset-3">
  	<div class="pull-left recommend-control">
  		<%= link_to content_tag(:i, "", :class => "fa fa-angle-left fa-3x"), "#", :id=>"prev-markets" if !@first_page %>
  	</div>
  	<div class="pull-right recommend-control">
  		<%= link_to content_tag(:i, "", :class => "fa fa-angle-right fa-3x"), "#", :id=>"next-markets" if !@last_page %>
  	</div>
  	<%= photo(market.featured, 200)%>
  	<br>
    <%= market.decorate.formatted_market_name %>
    <p> <%= link_to t(:recommend).capitalize, recommend_market_to_wish_path(wish, market), {:method => "post"} %> </p>
  </div>
<% end %>

app/views/markets/shared/views/_short_view.html.erb
<div class="panel panel-default panel-table" id="market_<%= market.id %>">
  
  <%= render partial: 'markets/shared/utils/title_and_actions_bar', locals: { market: market } %>

  <div class="market-list-each-container row">
    <div class = "col-md-8">
      <div class="market-list-section-title">
        <%= t(:information).capitalize %>
      </div>

      <div class="market-list-section-container">
        <div class = "row">
          <div class = "col-md-6">
            <%= market.market_featured_photo_filtered(200) %>
          </div>
          <div class = "col-md-6">
            <%= render partial: 'markets/shared/utils/description', locals: { market: market } %>
          </div>
        </div>
      </div>
    </div>
    
    <div class = "col-md-4">
      <div class="market-list-section-title"> <%= t(:coupon).capitalize %></div>
      <div class="market-list-section-container short-view-coupon-section">
        <div class="short-view-coupon-inner">
          <%= render "coupons/views/short_view", :market => market %>
        </div>
      </div>
    </div>

    <div class="market-badge">
      <div class="ribbon-badge <%= market.badges %>">
        <span class="badge-text"></span>
      </div>
    </div>
  </div> 
</div>

app/views/markets/shared/views/_slideshow.html.erb
<div class="item">
	<%= content_tag_for(:tr, market) do %>
    <%= link_to market do %>
    	<%= photo(market.featured, 300)%>
    	<div class = "market_name_label">
        <span><%= market.formatted_market_name %></span>
      </div>
      <div class = "market_description_label">
        <span><%= market.description %></span>
      </div>
    <% end %>
  <% end %> 
</div>

app/views/markets/shared/views/_slugs.html.erb
<div class="paginate">
  <%= paginate @markets %>
</div>

<% markets.each do |market| %>
  <% market = market.decorate %>
  <%= render partial: 'markets/shared/views/short_view', locals: { market: market } %>
<% end %>

app/views/markets/shared/views/_tooltip.html.erb
<div class="tooltip-container">
	<div class="tooltip-left">
		<%= market.market_photo_round_thumb(60, 60) %>
	</div>
	<div class="tooltip-right">
		<div class="market-name"> <%= market.formatted_market_name %> </div>
		<div class="market-description"> <%= market.description %> </div>
		<div class="market-tags"><%= market.hashtags %></div>
	</div>
	<div class="tooltip-buttons pull-right">
		<span> <%= link_to content_tag(:i, "", class: "fa fa-expand"), market_path(market), class: "tooltip-expand" %></span>
	</div>
</div>