config/routes.rb
PopUpStores::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:language)", locale: /en|es/ do 
    resources :markets, :only => [:index, :show] do
      collection do
        post :search, action: "search", as: 'search'
        get :search, action: "search"
        get :live_search, action: "live_search", path: "live_search"
      end
      post :publish
      post :publish_anyway
      post :unpublish
      post :archive
      get :make_pro_payment
      get :poster
      post :make_pro
      post :force_make_pro

      resource :statistic, controller: "statistic", :only => [] do
        get :market, :on => :member, :as => "show"
      end
    end

    get "/users/:id/dashboard", to: "users#user_dashboard", as: "user_dashboard"
    get "/users/admin", to: "users#admin", as: "admin"
    get "/users/:user_id/markets", to: "markets#list_user_markets", as: "user_markets"
    get "/published", to: "markets#list_published_markets", as: "published_markets"
    get "/list_recommend_markets", to: "markets#list_recommend_markets", as: "list_recommend_markets"

    get "/reindex", to: "markets#reindex", as: "market_reindex"
    get "/delete_index", to: "markets#delete_index", as: "market_delete_index"

    get "/users/gallery",  to: "users#gallery", as: "users_gallery"
    get "/users/like_market/:market_id",  to: "users#users_who_like_market", as: "users_who_like_market"
    get "/users/live_search", to: "users#live_search", path: "users_live_search"
    resources :users

    resources :slideshow_images, :except => [:show]
    resources :slideshow_texts, :except => [:show]

    resources :users do
      resources :markets, only: [:index, :new, :create, :edit, :update, :destroy]

      put :desactivate, :on => :member
      put :activate, :on => :member

      resource :role, controller: "role", :only => [:update] do
        get :change, :on => :member
      end

      resource :status, controller: "status", :only => [:update]

      resource :statistic, controller: "statistic", :only => [] do
        get :user, :on => :member, :as => "show"
      end

    end

    resources :subscriptions, :only => [:create] do

    end

    post "/unsubscribe", to: "subscriptions#unsubscribe", as: "unsubscribe"
    get "/users/:id/subscription", to: "users#subscription", as: "user_subscription"
    get "/users/:id/subscription_plan", to: "users#subscription_plan", as: "user_subscription_plan"

    resource :contact, controller: "contact", :only => [] do
      get :new, :on => :member
      post :create, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :market, :on => :member
    end

    resource :statistic, controller: "statistic", :only => [] do
      get :admin, :on => :member, :as => "show"
    end

    get "coupons/buy_coupon_form/:id", to: "coupons#buy_coupon_form", as: "buy_coupon_form"
    get "/coupons/gallery", to: "coupons#gallery", as: "coupons_gallery"
    get "/coupons/localizador/:transaction_id", to: "coupons#localizador", as: "localizador"
    get "coupons/digest", to:"coupons#digest", as: "last_transactions"
    resources :coupons, :only => [:show, :index] do
      post :coupon_payment, :on => :member
    end

    post "/coupons/:id/buy", to: "coupons#buy", as: "buy_coupon"
    get "/coupons/:user_id/bought_coupons_by_user", to: "coupons#bought_coupons_by_user", as: "bought_coupons_by_user"
    get "/coupons/:market_id/sold_coupons_by_market", to: "coupons#sold_coupons_by_market", as: "sold_coupons_by_market"

    get "/wishes/gallery", as: "wishes_gallery"
    get "/users/:user_id/wishes", to: "wishes#list_user_wishes", as: "user_wishes"
    post "/wishes/:id/recommend/:market_id", to: "wishes#recommend", as: "recommend_market_to_wish"
    get "/users/:user_id/wishes_gallery", to: "wishes#gallery_user_wishes", as: "gallery_user_wishes"

    resources :wishes

    get "/bargains/gallery", as: "bargains_gallery"
    get "/users/:user_id/bargains", to: "bargains#list_user_bargains", as: "user_bargains"
    get "/users/:user_id/bargains_gallery", to: "bargains#gallery_user_bargains", as: "gallery_user_bargains"
    resources :bargains

    get "/likes/:user_id", to: "markets#list_liked_markets", as: "user_likes"
    get "/like/:market_id",  to: 'users#like', as: 'like'
    get "/unlike/:market_id",  to: 'users#unlike', as: 'unlike'

    get "/follow/:user_id",  to: 'users#follow', as: 'follow_user'
    get "/unfollow/:user_id",  to: 'users#unfollow', as: 'unfollow_user'

    get "/photos/:id/edit", to: "photos#edit", as: 'edit_photo'
    post "/photos/:id/crop", to: "photos#crop", as: 'crop_photo'
    get "/users/:user_id/photos", to: "photos#list_user_photos", as: "user_photos"
    resources :photos, only: [:show, :index, :destroy]
    resources :gallery, only: [:show]

    get "/last_markets", to: "markets#list_last_markets", as: "last_markets"
    get "/pro_markets", to: "markets#list_pro_markets", as: "pro_markets"
    get "/slideshow", to: "markets#slideshow", as: "slideshow"

    get "/special_locations/list", as: "special_locations_list"
    get "/special_locations/gallery", as: "special_locations_gallery"
    get "/special_locations/get_location", as: "get_location", path: "get_location"
    resources :special_locations

    get "/tags/list", as: "tags_list"
    get "/tags/suggested", as: "suggested_tags"
    get "/tags/gallery", as: "tags_gallery"
    get "/tags/:tag/markets", to: "markets#list_tag_markets", as: "tag_markets"
    resources :tags
   
    get "/categories/list", as: "categories_list"
    get "/categories/gallery", as: "category_gallery"
    get "/category/:category_id/markets", to: "markets#list_category_markets", as: "category_markets"
    resources :categories

    get "static_pages/map", path: "/map", as: 'map'
    get "static_pages/buy_coupon_terms", as: "buy_coupon_terms"
    get "static_pages/sell_coupon_terms", as: "sell_coupon_terms"
    get "static_pages/go_premium_terms", as: "go_premium_terms"
    get "static_pages/go_vim_terms", as: "go_vim_terms"
    get "static_pages/about", as: "about"
    get "static_pages/privacy", as: "privacy"
    get "static_pages/terms", as: "terms"
    get "static_pages/settings", path: "/settings", as: "settings"
    get "static_pages/beta", path: "/beta", as: "beta"
    get "static_pages/open_market_menu", path: "/open_market", as: "open_market"

    get "static_pages/home", path: "/", as: 'home'
    root "static_pages#home"

  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount Attachinary::Engine => "/attachinary"

end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Slug

  slug :name

  validates :name, uniqueness: { message: "Category name must be unique" }
  field :name, type: String
  field :english, type: String
  field :style, type: String
  field :glyph, type: String
  field :color, type: String
  field :order, type: Integer

  has_attachment  :glyph_img, accept: [:png]
  accepts_nested_attributes_for :glyph_img

  has_one :photography, class_name: "Photo", as: :photographic, autobuild: true, dependent: :destroy
  accepts_nested_attributes_for :photography

  has_many :markets
  default_scope ->{ where(:name.ne => "").asc(:order)}
  
  def slug_candidates
    [
      :name
    ]
  end

  def destroy
    return false if markets_in_category?
    self.delete
  end

  def self.icon
    "fa-bars"
  end

  private

  def markets_in_category?
    self.markets.count > 0
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_resource :only => [:show, :edit, :destroy, :update]
  authorize_resource :except => [:show, :gallery, :list]

  def index
    @categories = Category.all
    respond_to do |format|
        format.html
        format.json {render json: @categories}
    end
  end

  def list
    @categories = Category.all
    render :layout => !request.xhr?
  end

  def gallery
    @categories = Category.all.limit(params['limit'] || 20 ) 
    render :layout => !request.xhr?
  end

  def show
    redirect_to categories_path
  end

  def new
    @category = Category.new
    render 'form'
  end

  def edit
    @category.glyph_img ||= Photo.new
    render 'form'
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, 
                      notice: ControllerNotice.success('created', 'category') }
      else
        format.html { redirect_to categories_path, 
                    flash: { error: ControllerNotice.fail('created', 'category') } }
      end 
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: ControllerNotice.success('updated', 'category') }
      else
        format.html { redirect_to categories_path, 
                    flash: { error: ControllerNotice.fail('updated', 'category') } }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_path, 
                      notice: ControllerNotice.success('deleted', 'category')}
      else  
        format.html { redirect_to categories_path, 
                    flash: { error: ControllerNotice.fail('deleted', 'category') } }
      end
    end
  end

  private
    def category_params
      params.require(:category).permit(:name, :english, :style, :order, :glyph, :color, :glyph_img,
                    photography_attributes: [:photo])
    end
end

app/helpers/category_helper.rb
module CategoryHelper
  def icon(category)
    if !category.glyph_img.nil?
     "<i class='fa icon'>#{cl_image_tag(category.glyph_img.path, :width => 16, :height => 16, :crop => :fill, :class => "icon")}</i>"
    else
      "<i class='fa #{category.glyph}'></i>"
    end
  end
  
  def formatted_button(category)
    "<button type='button' 
        class='theme theme-styled btn btn-sm category-theme-button btn-category' 
        style='background-color:#FFFFFF' 
        tile='#{category.style}'
        id='#{category.slug}'
        title='#{category.slug}'>
        #{icon(category)}
        <span>#{intl_name(category)}</span>
    </button> ".html_safe

  end

  
  def all_categories_button
      "<button type='button' 
          class='theme btn btn-sm btn-all-categories category-theme-button btn-category' 
          style='background-color:#FFFFFF' 
          tile='' 
          title='All categories'>
          <i class='fa fa-bars'>
          </i> <span>#{t :all_categories}</span>
       </button> ".html_safe  
  end

  def intl_name (category)
    if params['language'] == 'es'
      category.name
    else
      category.english
    end
  end
end

app/views/categories/_form_fields.html.erb
<%= javascript_include_tag "bootstrap-colorpicker" %>
<%= stylesheet_link_tag "bootstrap-colorpicker" %>

<div class="form-group">
  <%= f.input :name, input_html: { class: 'category-name', placeholder: "Category Name", :required => true } %>
</div>

<div class="form-group">
  <%= f.input :english, input_html: { class: 'english-category-name', placeholder: "in english...", :required => true } %>
</div>

<div class="form-group">
  <%= f.input :style, input_html: { class: 'category-style', placeholder: "Map Style", :required => true } %>
  <%= link_to "Create map styles", "https://www.mapbox.com", :target => "_blank" %>
</div>

<div class="form-group">
  <%= f.input :glyph, input_html: { class: 'category-glyph', placeholder: "Category glyph", :required => true } %>
  <%= link_to "Get icons", "http://fortawesome.github.io/Font-Awesome/icons/", :target => "_blank" %>
</div>

<div class="form-group">
  <%= f.input :color, input_html: { class: 'category-color colorpicker', placeholder: "Hex color ex. #673423", :required => true } %>
</div>

<div class="form-group">
  <%= f.input :order, input_html: { class: 'category-order', placeholder: "Order", :required => true } %>
</div>

<div class="form-group">
  <%= f.simple_fields_for :photography do |form_builder| %>
      <%= render 'photos/form', f: form_builder, required: true %>
  <% end %>
</div>

<div class="form-group">
  <p>Icon.png (maximun size 42 x 42 px)</p>
  <%= f.input :glyph_img, as: :attachinary %>
</div>

<script>
$( document ).ready(function() {
  $('.colorpicker').colorpicker();
});
</script>

app/views/categories/_table_fields.html.erb
<div class="col-md-2"> 
  <div class="table-photo-container">
    <%= photo(entity.photography, 120) %>
    <%= render partial: 'photos/utils/actions', locals: { photo: entity.photography} %>
  </div>
</div>

<div class="col-md-3"> 
  <em> Name:</em> <%= link_to entity.name, category_markets_path(entity) %> (<%= entity.markets.count %>)<br>
  <em> English name:</em> <%= entity.english %><br>
  <em> Slug:</em> <%= entity.slug %>
  <em> Order:</em> <%= entity.order %>
</div> 

<div class="col-md-2"> 
  <%= formatted_button(entity) %>
</div> 

<div class="col-md-2"> 
  <%= entity.style %>
</div> 

app/views/categories/form.html.erb
<%= form(@category) %>

app/views/categories/gallery.html.erb
<div class="panel panel-default panel-table panel-table-last">

  <div class="panel-heading table-title">
    <%= t(:categories).capitalize %>
  </div>

  <div class = "row category-gallery">
    <% @categories.each do |category| %>
      <div class = "item">
        <div class = "photo center" data-name="<%= category.slug %>">
          <%= cl_image_tag(category.glyph_img.path, 
            :width => 50, :height => 50, :crop => :fill) if category.glyph_img.present? %>
        </div>
        <div class="center">
          <%= intl_name(category) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
$( document ).ready(function() {
  $(".category-gallery .item .photo").click(function(){
    $("#category_category_id").val($(this).data("name"));
    $("#search_market").submit();
  });
});
</script>

app/views/categories/index.html.erb
<%= table(@categories) %>

app/views/categories/list.html.erb
<% @categories.each do |category| %>
  <li class="registered-user-action">
    <a class="explore-link-categories" href="#" data-name="<%= category.slug %>">
      <%= intl_name(category) %>
      <i class="fa fa-angle-right explore-arrow"></i>
    </a>
  </li>
<% end %>

<script>
  $(".explore-link-categories").click(function(){
    $("#category_category_id").val($(this).data("name"));
    $("#search_market").submit();
  });
</script>